name: "Godot CI/CD Export"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  export-game:
    name: Export Godot Project
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.2.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Export Templates Location
        run: |
          mkdir -p ~/.local/share/godot/export_templates
          cp -r /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/

      - name: Setup Export Directory
        run: mkdir -v -p build/web

      - name: Export Game
        run: godot --headless --path MySimpleGame --export-release "Web" ../build/web/index.html

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: godot-web-build
          path: build/web
          overwrite: true
